hub:
    cookieSecret: "821504fe5879054fd5e03a380ba90bfb4b95b73c3c255bac3dccb5855575a855"
    image:
        name: jackmoore/hub
        tag: 4efe0b7e13ec3ae83f2acac4fb803350
    # extraConfig: |
    #     c.JupyterHub.load_groups = {
    #         'shared': [
    #             'jackmoore5021',
    #             'willingc',
    #         ]
    #     }
    #     c.JupyterHub.services = [
    #         {
    #             'name': 'shared-notebook',
    #             'url': 'http://127.0.0.1:9999',
    #             'command': [
    #                 'jupyterhub-singleuser',
    #                 '--group=shared',
    #                 '--debug',
    #             ],
    #         }
    #     ]
proxy:
    secretToken: "3366e8fc0748609355ac37b5cffc252c63be3a1f17e6ebe5f29c1801413810d7"
singleuser:
    extraEnv:
        EDITOR: vim
    storage:
        type: dynamic
        static:
            pvcName: null
            subPath: "{username}"
        capacity: 10Gi
        homeMountPath: /home/jovyan/work
    image:
        name: jackmoore/notebook
        tag: 4efe0b7e13ec3ae83f2acac4fb803350
    lifecycleHooks:
        postStart:
            exec:
                command: ["/bin/sh","-c","cp -Rf /$HOME/.starterNotebooks/. $HOME/work" ]
auth:
    type: github
    github:
        clientId: "42066cc02d3b6ac2f687"
        clientSecret: "853d2d8af2415d33e1b26811cf534927ca28e6a4"
        callbackUrl: "http://130.211.206.35/hub/oauth_callback"
cull:
    enabled: true
    timeout: 3600
    every: 600
