# engines go here
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: engine-1
  name: engine-1
spec:
  type: NodePort
  ports:
  - name: "8003"
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    service: engine-1
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: engine-1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: engine-1
    spec:
      containers:
      - env:
        - name: CONNECT_PREFIX
          value: "https://connect:8001"
        image: fastscore/engine-x:latest
        name: engine-1
        ports:
        - containerPort: 8003
          protocol: TCP
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}